# Generated by Django 4.2.29 on 2026-04-07 17:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lili_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='fecha_solicitud',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariolibro',
            name='fecha_anadido',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuariolibro',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lili_api.serie'),
        ),
        migrations.CreateModel(
            name='LibroCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lili_api.categoria')),
                ('usuario_libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lili_api.usuariolibro')),
            ],
            options={
                'unique_together': {('usuario_libro', 'categoria')},
            },
        ),
        migrations.AlterField(
            model_name='usuariolibro',
            name='categorias',
            field=models.ManyToManyField(related_name='libros_usuario', through='lili_api.LibroCategoria', to='lili_api.categoria'),
        ),
    ]
